csv:

output_dir: "output"
save_previews: false

tiling:
  params:
    target_spacing_um: 0.5 # spacing at which to tile the slide, in microns per pixel
    target_tile_size_px: 224 # size of the tiles to extract, in pixels

model:
  level: "tile" # level at which to extract the features ("tile", "region" or "slide")
  arch: "hibou-b" # Hibou model architectures, options: ("hibou-b", "hibou-L")
  name: "hibou"

speed:
  fp16: true # use mixed precision during model inference