csv: ""

output_dir: "output"
save_previews: false

tiling:
  params:
    target_spacing_um: 0.5
    target_tile_size_px: 224

model:
  level: "tile"
  name: "panda-vit-s"
  pretrained_weights: "/path/to/model/weights.pt"

speed:
  precision: "fp32"
