csv: "/data/pathology/projects/clement/leopard/csvs/brazil-slide2vec-august-2025-revision.csv"

output_dir: "/data/pathology/projects/clement/discern/pathojepa/slide2vec"

tiling:
  preview:
    save: false
  params:
    target_spacing_um: 0.5
    tolerance: 0.05
    target_tile_size_px: 2048
    tissue_threshold: 0.1
  seg_params:
    downsample: 64
  filter_params:
    ref_tile_size: 256

model:
  level: "region"
  name: "pathojepa"
  arch: "vit_small"
  pretrained_weights: "/data/pathology/projects/clement/discern/pathojepa/runs/dmky8lh7/jepa-pathorob-latest.pth.tar"
  input_size: 224
  patch_size: 256
  token_size: 16
  normalize_embeddings: false
  batch_size: 1

speed:
  precision: "fp32"

wandb:
  enable: true
  project: "leopard"
  username: "clemsg"
  exp_name: "features"
  tags: ["features", "dev", "${model.name}", "${model.level}", "${tiling.params.target_tile_size_px}"]
