csv:

output_dir: "output"
tiling:
  preview:
    save: false
  params:
    target_spacing_um: 0.5
    target_tile_size_px: 224

model:
  level: "slide"
  name: "prism"
  save_tile_embeddings: true
  save_latents: false

speed:
  precision: "fp16"
