csv:

output_dir: "output"
tiling:
  preview:
    save: false
  params:
    target_spacing_um: 0.5
    target_tile_size_px: 256

model:
  level: "slide"
  name: "prov-gigapath"
  save_tile_embeddings: true

speed:
  precision: "fp16"
