name: Lint

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run-linters:
    name: Run linters
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9
          cache: 'pip'
          cache-dependency-path: '**/lint*.txt'
      - name: Install Python (development) dependencies
        run: |
          pip install -r lint.txt
      - name: Run flake8
        run: |
          flake8 --ignore=E501,F401,E203,W503
      - name: Run black
        if: always()
        run: |
          black --check slide2vec
      - name: Run pylint
        if: always()
        run: |
          pylint --exit-zero slide2vec